### ISSUE TITLE
Metrics present on custom metrics endpoint but controller says metric not found

### ISSUE THREAD

**Issue by criscola** [intel/platform-aware-scheduling#103]
Hello, I tried to add a custom metric myself but I'm having my pods in Pending. Then I simply tried to follow the health demo tutorial but I have the same problem. Upon inspection the controller's logs say the metric is not present `no metric health_metric found " component="controller"` but if I run `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/nodes/*/health_metric" | jq .` I can see them...  so scraping from prometheus to Kubernetes works. Do you have any idea what could be the problem?

**Comment by togashidm** [comment]
Hi, thank you to reach us. Since you are able to see the metrics and the pods are in a Pending state, perhaps tas and default scheduler are not talking to each other.   Have you run the configuration [script](https://github.com/intel/platform-aware-scheduling/blob/master/telemetry-aware-scheduling/deploy/extender-configuration/configure-scheduler.sh) ? This can happen on earlier versions of k8s.

**Comment by criscola** [comment]
Yes actually we are running an old version for the moment (v1.21), but the problem was I didn't run the script on the master node. Now it works. Thank you very much for the quick response!
